--- #YAML:1.0
name:               Image-Base-Prima
version:            3
abstract:           Image::Base drawing into Prima windows and images.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Image::Base:   1.12
    perl:          5.005
    Prima:         0
    Prima::noX11:  0
    Test:          0
    Test::More:    0
resources:
    homepage:  http://user42.tuxfamily.org/image-base-prima/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Pod::Simple::HTML:  0
            Smart::Comments:    0
            warnings::unused:   0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::Pod:           1.00
            Test::YAML::Meta:    0.15
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
recommends:
    Prima:  1.29
